insert into car (make, model, price) values ('Lexus', 'LS', 28271);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 9007);
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', 48875);
insert into car (make, model, price) values ('GMC', '3500', 54783);
insert into car (make, model, price) values ('Dodge', 'Charger', 27562);
insert into car (make, model, price) values ('Mercury', 'Sable', 72941);
insert into car (make, model, price) values ('Mitsubishi', 'Endeavor', 48566);
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', 76498);
insert into car (make, model, price) values ('GMC', 'Savana 2500', 21443);
insert into car (make, model, price) values ('Pontiac', 'Bonneville', 7250);
insert into car (make, model, price) values ('Chevrolet', 'G-Series G30', 22411);
insert into car (make, model, price) values ('Suzuki', 'Equator', 3765);
insert into car (make, model, price) values ('Dodge', 'Colt', 40264);
insert into car (make, model, price) values ('Dodge', 'Nitro', 33196);
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', 7330);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLR McLaren', 92804);
insert into car (make, model, price) values ('Nissan', 'Maxima', 19369);
insert into car (make, model, price) values ('Subaru', 'Impreza', 25900);
insert into car (make, model, price) values ('Oldsmobile', 'Silhouette', 59773);
insert into car (make, model, price) values ('Chevrolet', 'Lumina', 30015);
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', 77648);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 43741);
insert into car (make, model, price) values ('Bentley', 'Continental', 6197);
insert into car (make, model, price) values ('BMW', '6 Series', 66750);
insert into car (make, model, price) values ('Dodge', 'Avenger', 9699);
insert into car (make, model, price) values ('Volkswagen', 'GTI', 37578);
insert into car (make, model, price) values ('Ford', 'F250', 89322);
insert into car (make, model, price) values ('Acura', 'NSX', 24633);
insert into car (make, model, price) values ('Dodge', 'Omni', 83760);
insert into car (make, model, price) values ('Ford', 'E350', 63719);
insert into car (make, model, price) values ('Pontiac', 'Firefly', 82277);
insert into car (make, model, price) values ('Mitsubishi', 'GTO', 53783);
insert into car (make, model, price) values ('Lincoln', 'MKT', 90814);
insert into car (make, model, price) values ('Mazda', 'B-Series Plus', 25621);
insert into car (make, model, price) values ('Mercedes-Benz', 'W201', 81951);
insert into car (make, model, price) values ('Honda', 'CR-Z', 29639);
insert into car (make, model, price) values ('Audi', 'Q7', 37320);
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', 23585);
insert into car (make, model, price) values ('Buick', 'Regal', 59151);
insert into car (make, model, price) values ('Infiniti', 'IPL G', 19126);
insert into car (make, model, price) values ('Infiniti', 'FX', 3784);
insert into car (make, model, price) values ('Lincoln', 'MKZ', 69472);
insert into car (make, model, price) values ('BMW', '530', 99915);
insert into car (make, model, price) values ('Jaguar', 'XK Series', 14177);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 3500', 23676);
insert into car (make, model, price) values ('GMC', '1500 Club Coupe', 85747);
insert into car (make, model, price) values ('Mercury', 'Mountaineer', 71109);
insert into car (make, model, price) values ('Chevrolet', 'Classic', 5737);
insert into car (make, model, price) values ('Ford', 'F150', 15922);
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', 94906);
insert into car (make, model, price) values ('Subaru', 'Forester', 68851);
insert into car (make, model, price) values ('Pontiac', 'Firebird', 88484);
insert into car (make, model, price) values ('Pontiac', 'Firefly', 30919);
insert into car (make, model, price) values ('GMC', 'Envoy XL', 16506);
insert into car (make, model, price) values ('Chevrolet', 'Astro', 91550);
insert into car (make, model, price) values ('Jaguar', 'XF', 25190);
insert into car (make, model, price) values ('Infiniti', 'Q', 24758);
insert into car (make, model, price) values ('Hyundai', 'Veracruz', 48682);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', 91756);
insert into car (make, model, price) values ('Volvo', 'XC60', 92136);
insert into car (make, model, price) values ('Toyota', 'Tundra', 38094);
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', 37323);
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', 76363);
insert into car (make, model, price) values ('Toyota', 'TundraMax', 18060);
insert into car (make, model, price) values ('Austin', 'Mini Cooper', 65375);
insert into car (make, model, price) values ('Bentley', 'Continental GT', 36772);
insert into car (make, model, price) values ('Ford', 'LTD Crown Victoria', 54292);
insert into car (make, model, price) values ('Porsche', '911', 21599);
insert into car (make, model, price) values ('Nissan', 'Altima', 17114);
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', 81973);
insert into car (make, model, price) values ('Dodge', 'Ram 3500 Club', 29008);
insert into car (make, model, price) values ('Kia', 'Amanti', 86307);
insert into car (make, model, price) values ('GMC', 'Sonoma', 60636);
insert into car (make, model, price) values ('Dodge', 'Ram 2500', 82775);
insert into car (make, model, price) values ('Cadillac', 'SRX', 74513);
insert into car (make, model, price) values ('Infiniti', 'EX', 41061);
insert into car (make, model, price) values ('Subaru', 'Legacy', 65655);
insert into car (make, model, price) values ('Ford', 'Mustang', 86710);
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', 83857);
insert into car (make, model, price) values ('Volvo', 'C70', 33550);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 54087);
insert into car (make, model, price) values ('Chevrolet', 'Malibu', 46262);
insert into car (make, model, price) values ('Lincoln', 'Navigator L', 10722);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 24327);
insert into car (make, model, price) values ('Audi', 'S8', 47416);
insert into car (make, model, price) values ('GMC', 'Yukon', 75591);
insert into car (make, model, price) values ('Ford', 'F150', 75996);
insert into car (make, model, price) values ('Oldsmobile', 'Intrigue', 21023);
insert into car (make, model, price) values ('Pontiac', 'Aztek', 87140);
insert into car (make, model, price) values ('Lotus', 'Evora', 48128);
insert into car (make, model, price) values ('Volkswagen', 'Jetta', 58955);
insert into car (make, model, price) values ('Ford', 'Escape', 63260);
insert into car (make, model, price) values ('GMC', 'Savana Cargo Van', 11527);
insert into car (make, model, price) values ('Volkswagen', 'Golf', 23777);
insert into car (make, model, price) values ('Infiniti', 'FX', 86678);
insert into car (make, model, price) values ('Chevrolet', 'Camaro', 16672);
insert into car (make, model, price) values ('Acura', 'MDX', 44123);
insert into car (make, model, price) values ('Dodge', 'Shadow', 96290);
insert into car (make, model, price) values ('Lexus', 'RX', 66180);
insert into car (make, model, price) values ('Dodge', 'Intrepid', 46416);
insert into car (make, model, price) values ('Infiniti', 'JX', 14499);
insert into car (make, model, price) values ('Saab', '9-3', 15551);
insert into car (make, model, price) values ('Volkswagen', 'Corrado', 94123);
insert into car (make, model, price) values ('Toyota', 'TundraMax', 90797);
insert into car (make, model, price) values ('Chevrolet', 'Silverado', 76452);
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', 59596);
insert into car (make, model, price) values ('Jaguar', 'XJ', 32395);
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', 41535);
insert into car (make, model, price) values ('GMC', 'Savana 2500', 45381);
insert into car (make, model, price) values ('Lexus', 'LX', 18238);
insert into car (make, model, price) values ('Acura', 'Vigor', 89531);
insert into car (make, model, price) values ('Toyota', 'Corolla', 32721);
insert into car (make, model, price) values ('Toyota', 'Tacoma Xtra', 67532);
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', 22812);
insert into car (make, model, price) values ('Honda', 'Passport', 89666);
insert into car (make, model, price) values ('Lexus', 'RX Hybrid', 35460);
insert into car (make, model, price) values ('Ram', '1500', 76675);
insert into car (make, model, price) values ('Oldsmobile', 'Ciera', 60334);
insert into car (make, model, price) values ('GMC', 'Sierra 2500', 84177);
insert into car (make, model, price) values ('Lexus', 'RX', 83648);
insert into car (make, model, price) values ('Saab', '9-2X', 16110);
insert into car (make, model, price) values ('Infiniti', 'QX', 86107);
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', 65461);
insert into car (make, model, price) values ('Dodge', 'Ram Wagon B150', 11820);
insert into car (make, model, price) values ('GMC', 'Suburban 1500', 38509);
insert into car (make, model, price) values ('Mercury', 'Tracer', 11476);
insert into car (make, model, price) values ('MINI', 'Clubman', 93467);
insert into car (make, model, price) values ('Nissan', 'Titan', 49206);
insert into car (make, model, price) values ('Mitsubishi', 'Tredia', 3818);
insert into car (make, model, price) values ('Volvo', 'XC70', 8942);
insert into car (make, model, price) values ('Rolls-Royce', 'Phantom', 84291);
insert into car (make, model, price) values ('Ford', 'F250', 82992);
insert into car (make, model, price) values ('Volvo', '940', 21921);
insert into car (make, model, price) values ('Isuzu', 'Hombre', 11128);
insert into car (make, model, price) values ('Buick', 'Regal', 87860);
insert into car (make, model, price) values ('Geo', 'Metro', 84425);
insert into car (make, model, price) values ('Subaru', 'Legacy', 15117);
insert into car (make, model, price) values ('Ford', 'F150', 4471);
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass Supreme', 54712);
insert into car (make, model, price) values ('Lincoln', 'Aviator', 84432);
insert into car (make, model, price) values ('Chevrolet', 'Blazer', 40305);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', 45206);
insert into car (make, model, price) values ('Infiniti', 'Q', 94963);
insert into car (make, model, price) values ('BMW', 'M5', 41520);
insert into car (make, model, price) values ('Nissan', '200SX', 57670);
insert into car (make, model, price) values ('Hyundai', 'Genesis', 73174);
insert into car (make, model, price) values ('Cadillac', 'DeVille', 11118);
insert into car (make, model, price) values ('Pontiac', 'Vibe', 72204);
insert into car (make, model, price) values ('Panoz', 'Esperante', 52624);
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', 42176);
insert into car (make, model, price) values ('Audi', '4000s', 61251);
insert into car (make, model, price) values ('Mitsubishi', 'Cordia', 12542);
insert into car (make, model, price) values ('Nissan', '350Z', 89766);
insert into car (make, model, price) values ('Eagle', 'Talon', 46274);
insert into car (make, model, price) values ('Ford', 'Thunderbird', 59847);
insert into car (make, model, price) values ('Volvo', '240', 70692);
insert into car (make, model, price) values ('Buick', 'LeSabre', 80469);
insert into car (make, model, price) values ('Chevrolet', 'Cruze', 35947);
insert into car (make, model, price) values ('Lexus', 'LX', 27277);
insert into car (make, model, price) values ('Daewoo', 'Lanos', 47360);
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', 78832);
insert into car (make, model, price) values ('Volkswagen', 'Fox', 25348);
insert into car (make, model, price) values ('Ford', 'Aerostar', 57339);
insert into car (make, model, price) values ('Infiniti', 'I', 63617);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', 96235);
insert into car (make, model, price) values ('Buick', 'Park Avenue', 71346);
insert into car (make, model, price) values ('Toyota', 'Tundra', 54883);
insert into car (make, model, price) values ('Chevrolet', 'Uplander', 35518);
insert into car (make, model, price) values ('Lincoln', 'LS', 42606);
insert into car (make, model, price) values ('Saab', '9-7X', 57050);
insert into car (make, model, price) values ('Smart', 'Fortwo', 55882);
insert into car (make, model, price) values ('Dodge', 'Ram', 74315);
insert into car (make, model, price) values ('Mitsubishi', 'RVR', 13832);
insert into car (make, model, price) values ('Nissan', 'Leaf', 55645);
insert into car (make, model, price) values ('Ford', 'ZX2', 68361);
insert into car (make, model, price) values ('Porsche', '911', 82536);
insert into car (make, model, price) values ('Chevrolet', 'Astro', 39895);
insert into car (make, model, price) values ('GMC', 'Yukon', 23433);
insert into car (make, model, price) values ('Dodge', 'Ram Van 3500', 35254);
insert into car (make, model, price) values ('Dodge', 'Ramcharger', 94293);
insert into car (make, model, price) values ('Ford', 'Mustang', 95326);
insert into car (make, model, price) values ('Chevrolet', 'Corvair', 71048);
insert into car (make, model, price) values ('Ford', 'E250', 12073);
insert into car (make, model, price) values ('Mercury', 'Capri', 94621);
insert into car (make, model, price) values ('Toyota', 'RAV4', 38076);
insert into car (make, model, price) values ('Dodge', 'Ram 2500', 30647);
insert into car (make, model, price) values ('Bentley', 'Continental Flying Spur', 89398);
insert into car (make, model, price) values ('Chevrolet', 'Beretta', 92895);
insert into car (make, model, price) values ('Honda', 'Civic', 13794);
insert into car (make, model, price) values ('Volvo', 'C30', 40310);
insert into car (make, model, price) values ('Acura', 'RL', 46344);
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', 2764);
insert into car (make, model, price) values ('Hyundai', 'Genesis Coupe', 63882);
insert into car (make, model, price) values ('Dodge', 'Ram Van B350', 34503);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 24582);
insert into car (make, model, price) values ('GMC', '2500', 26007);
insert into car (make, model, price) values ('Volkswagen', 'GTI', 51902);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 2909);
insert into car (make, model, price) values ('Nissan', 'Armada', 3759);
insert into car (make, model, price) values ('Dodge', 'Neon', 18372);
insert into car (make, model, price) values ('Saturn', 'S-Series', 98293);
insert into car (make, model, price) values ('Dodge', 'Charger', 65103);
insert into car (make, model, price) values ('Ford', 'E-Series', 17490);
insert into car (make, model, price) values ('Oldsmobile', '88', 74986);
insert into car (make, model, price) values ('Chrysler', 'New Yorker', 50285);
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', 39931);
insert into car (make, model, price) values ('Subaru', 'Justy', 30747);
insert into car (make, model, price) values ('Volvo', 'V70', 53697);
insert into car (make, model, price) values ('Hyundai', 'XG350', 61919);
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', 87032);
insert into car (make, model, price) values ('Mazda', 'Mazda3', 1407);
insert into car (make, model, price) values ('Cadillac', 'STS', 62277);
insert into car (make, model, price) values ('Ford', 'Thunderbird', 68567);
insert into car (make, model, price) values ('Toyota', 'Tundra', 57462);
insert into car (make, model, price) values ('Volvo', 'V70', 59420);
insert into car (make, model, price) values ('Mercury', 'Cougar', 18747);
insert into car (make, model, price) values ('Honda', 'Civic', 28610);
insert into car (make, model, price) values ('Jaguar', 'XJ Series', 79783);
insert into car (make, model, price) values ('Mazda', 'Mazdaspeed6', 13588);
insert into car (make, model, price) values ('Infiniti', 'EX', 6303);
insert into car (make, model, price) values ('Acura', 'ZDX', 66564);
insert into car (make, model, price) values ('GMC', 'Savana 3500', 99063);
insert into car (make, model, price) values ('Land Rover', 'LR3', 42542);
insert into car (make, model, price) values ('Honda', 'S2000', 55770);
insert into car (make, model, price) values ('Ford', 'E-Series', 71380);
insert into car (make, model, price) values ('Hyundai', 'Veracruz', 61849);
insert into car (make, model, price) values ('Chevrolet', 'Express', 8256);
insert into car (make, model, price) values ('Honda', 'Accord', 40263);
insert into car (make, model, price) values ('Mazda', '626', 38407);
insert into car (make, model, price) values ('Pontiac', 'Montana', 58390);
insert into car (make, model, price) values ('Porsche', 'Cayman', 59251);
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', 25530);
insert into car (make, model, price) values ('Porsche', '911', 3353);
insert into car (make, model, price) values ('Volvo', 'C70', 68740);
insert into car (make, model, price) values ('Scion', 'xD', 8006);
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', 13664);
insert into car (make, model, price) values ('Ford', 'Expedition EL', 49354);
insert into car (make, model, price) values ('GMC', 'Savana 1500', 98943);
insert into car (make, model, price) values ('BMW', '530', 40238);
insert into car (make, model, price) values ('Mercury', 'Mountaineer', 31803);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 81843);
insert into car (make, model, price) values ('Volkswagen', 'Golf III', 18111);
insert into car (make, model, price) values ('Hummer', 'H2', 44479);
insert into car (make, model, price) values ('Porsche', '928', 65373);
insert into car (make, model, price) values ('BMW', '1 Series', 38867);
insert into car (make, model, price) values ('Dodge', 'Durango', 64667);
insert into car (make, model, price) values ('Porsche', 'Boxster', 18869);
insert into car (make, model, price) values ('Jaguar', 'S-Type', 90243);
insert into car (make, model, price) values ('Toyota', 'Camry Hybrid', 75816);
insert into car (make, model, price) values ('GMC', 'Savana 1500', 16551);
insert into car (make, model, price) values ('Mazda', 'MPV', 28193);
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', 43125);
insert into car (make, model, price) values ('Ford', 'Thunderbird', 31019);
insert into car (make, model, price) values ('Toyota', 'Camry Solara', 67334);
insert into car (make, model, price) values ('Geo', 'Prizm', 96978);
insert into car (make, model, price) values ('Pontiac', 'Firebird', 93178);
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', 28101);
insert into car (make, model, price) values ('Mercedes-Benz', 'M-Class', 11676);
insert into car (make, model, price) values ('Porsche', '968', 24369);
insert into car (make, model, price) values ('Cadillac', 'SRX', 5571);
insert into car (make, model, price) values ('Pontiac', 'Firefly', 79839);
insert into car (make, model, price) values ('Chrysler', 'Prowler', 21388);
insert into car (make, model, price) values ('Oldsmobile', 'Ciera', 30139);
insert into car (make, model, price) values ('BMW', '7 Series', 56684);
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', 1483);
insert into car (make, model, price) values ('Dodge', 'Ram Wagon B250', 93750);
insert into car (make, model, price) values ('Subaru', 'Legacy', 31723);
insert into car (make, model, price) values ('Isuzu', 'Hombre Space', 42666);
insert into car (make, model, price) values ('Ford', 'Taurus', 32126);
insert into car (make, model, price) values ('Ford', 'E-Series', 56938);
insert into car (make, model, price) values ('Jeep', 'Cherokee', 47797);
insert into car (make, model, price) values ('Nissan', 'Sentra', 14895);
insert into car (make, model, price) values ('Toyota', 'Prius Plug-in', 59090);
insert into car (make, model, price) values ('Chevrolet', 'Equinox', 8698);
insert into car (make, model, price) values ('Mazda', 'Tribute', 78205);
insert into car (make, model, price) values ('Lexus', 'ES', 55854);
insert into car (make, model, price) values ('Ford', 'Mustang', 57761);
insert into car (make, model, price) values ('Acura', 'MDX', 49249);
insert into car (make, model, price) values ('Scion', 'iQ', 95599);
insert into car (make, model, price) values ('Volvo', 'XC70', 13475);
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', 39505);
insert into car (make, model, price) values ('Jaguar', 'S-Type', 35369);
insert into car (make, model, price) values ('Saturn', 'Aura', 74874);
insert into car (make, model, price) values ('Mercedes-Benz', 'R-Class', 75597);
insert into car (make, model, price) values ('Volkswagen', 'Jetta', 21537);
insert into car (make, model, price) values ('Porsche', 'Boxster', 22250);
insert into car (make, model, price) values ('Volkswagen', 'GTI', 20341);
insert into car (make, model, price) values ('Mazda', 'MX-6', 48556);
insert into car (make, model, price) values ('Saab', '9000', 99645);
insert into car (make, model, price) values ('Volvo', 'C70', 11539);
insert into car (make, model, price) values ('Hyundai', 'Veracruz', 46201);
insert into car (make, model, price) values ('Nissan', 'Sentra', 24315);
insert into car (make, model, price) values ('Maybach', '62', 3320);
insert into car (make, model, price) values ('Dodge', 'Nitro', 85010);
insert into car (make, model, price) values ('GMC', 'Savana 1500', 82150);
insert into car (make, model, price) values ('Ford', 'Ranger', 11167);
insert into car (make, model, price) values ('Porsche', 'Boxster', 35254);
insert into car (make, model, price) values ('Mitsubishi', 'Outlander', 78979);
insert into car (make, model, price) values ('Dodge', 'Durango', 36283);
insert into car (make, model, price) values ('Nissan', 'Quest', 59727);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 79171);
insert into car (make, model, price) values ('Jaguar', 'XJ', 89182);
insert into car (make, model, price) values ('Chevrolet', '3500', 38585);
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', 5841);
insert into car (make, model, price) values ('Ford', 'F150', 2393);
insert into car (make, model, price) values ('Acura', 'RL', 67028);
insert into car (make, model, price) values ('Plymouth', 'Voyager', 68577);
insert into car (make, model, price) values ('Lexus', 'LX', 16891);
insert into car (make, model, price) values ('Scion', 'xB', 2056);
insert into car (make, model, price) values ('Dodge', 'Ram 1500', 48173);
insert into car (make, model, price) values ('Dodge', 'Viper RT/10', 18550);
insert into car (make, model, price) values ('GMC', 'Sierra 1500', 73234);
insert into car (make, model, price) values ('GMC', 'Suburban 2500', 54895);
insert into car (make, model, price) values ('Chrysler', '300M', 77192);
insert into car (make, model, price) values ('Land Rover', 'Freelander', 71397);
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', 56345);
insert into car (make, model, price) values ('Ford', 'F-Series', 92834);
insert into car (make, model, price) values ('Infiniti', 'G', 75318);
insert into car (make, model, price) values ('Toyota', 'Camry', 40627);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 80032);
insert into car (make, model, price) values ('Chevrolet', 'Metro', 51243);
insert into car (make, model, price) values ('Nissan', 'Altima', 8801);
insert into car (make, model, price) values ('Cadillac', 'Escalade EXT', 32567);
insert into car (make, model, price) values ('Lincoln', 'MKS', 98331);
insert into car (make, model, price) values ('Acura', 'Vigor', 30688);
insert into car (make, model, price) values ('Ford', 'Transit Connect', 49661);
insert into car (make, model, price) values ('Mercury', 'Lynx', 72248);
insert into car (make, model, price) values ('Nissan', '240SX', 41521);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', 4120);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', 9866);
insert into car (make, model, price) values ('Toyota', 'Prius', 69184);
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', 99144);
insert into car (make, model, price) values ('Ford', 'Lightning', 2536);
insert into car (make, model, price) values ('Nissan', 'Versa', 98435);
insert into car (make, model, price) values ('Plymouth', 'Voyager', 8292);
insert into car (make, model, price) values ('Volvo', 'V90', 43497);
insert into car (make, model, price) values ('Audi', 'S8', 9612);
insert into car (make, model, price) values ('Buick', 'Regal', 42491);
insert into car (make, model, price) values ('Chevrolet', 'S10', 68241);
insert into car (make, model, price) values ('Ford', 'Festiva', 71710);
insert into car (make, model, price) values ('Nissan', 'Xterra', 6036);
insert into car (make, model, price) values ('Land Rover', 'LR4', 66749);
insert into car (make, model, price) values ('Ford', 'F-Series Super Duty', 73830);
insert into car (make, model, price) values ('Mitsubishi', 'Lancer Evolution', 47175);
insert into car (make, model, price) values ('Audi', 'S8', 23807);
insert into car (make, model, price) values ('Audi', 'V8', 12809);
insert into car (make, model, price) values ('Ford', 'Explorer Sport Trac', 3908);
insert into car (make, model, price) values ('Volvo', 'XC90', 55108);
insert into car (make, model, price) values ('Mazda', 'B-Series', 80914);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLR McLaren', 56191);
insert into car (make, model, price) values ('Dodge', 'Ram 3500 Club', 81924);
insert into car (make, model, price) values ('Daewoo', 'Lanos', 56945);
insert into car (make, model, price) values ('Plymouth', 'Voyager', 2818);
insert into car (make, model, price) values ('Maybach', 'Landaulet', 69700);
insert into car (make, model, price) values ('Saab', '900', 58031);
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', 19038);
insert into car (make, model, price) values ('Ford', 'Club Wagon', 5514);
insert into car (make, model, price) values ('Dodge', 'Dakota', 27300);
insert into car (make, model, price) values ('Ford', 'F450', 23453);
insert into car (make, model, price) values ('Audi', '5000S', 59318);
insert into car (make, model, price) values ('GMC', '3500', 59662);
insert into car (make, model, price) values ('Oldsmobile', 'Achieva', 18210);
insert into car (make, model, price) values ('Suzuki', 'Swift', 65522);
insert into car (make, model, price) values ('Mercedes-Benz', 'GLK-Class', 82849);
insert into car (make, model, price) values ('Mitsubishi', 'GTO', 39565);
insert into car (make, model, price) values ('Infiniti', 'Q', 82292);
insert into car (make, model, price) values ('Toyota', 'Prius', 56672);
insert into car (make, model, price) values ('Infiniti', 'FX', 55117);
insert into car (make, model, price) values ('Lexus', 'GS', 16551);
insert into car (make, model, price) values ('GMC', 'Sonoma', 16191);
insert into car (make, model, price) values ('Suzuki', 'Kizashi', 39229);
insert into car (make, model, price) values ('Audi', 'Q5', 57269);
insert into car (make, model, price) values ('Mazda', 'Familia', 26097);
insert into car (make, model, price) values ('Volvo', 'V40', 18797);
insert into car (make, model, price) values ('Cadillac', 'SRX', 15437);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', 47003);
insert into car (make, model, price) values ('Mitsubishi', 'Starion', 7283);
insert into car (make, model, price) values ('Volkswagen', 'Jetta', 6392);
insert into car (make, model, price) values ('Ford', 'Edge', 80257);
insert into car (make, model, price) values ('Volkswagen', 'Eos', 51487);
insert into car (make, model, price) values ('Volvo', 'V50', 41820);
insert into car (make, model, price) values ('Buick', 'Skylark', 59726);
insert into car (make, model, price) values ('Cadillac', 'SRX', 83196);
insert into car (make, model, price) values ('Pontiac', 'Grand Am', 8537);
insert into car (make, model, price) values ('GMC', 'Sierra 3500', 27086);
insert into car (make, model, price) values ('Toyota', 'Celica', 30212);
insert into car (make, model, price) values ('Lincoln', 'Town Car', 34554);
insert into car (make, model, price) values ('Lincoln', 'Continental', 75363);
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', 84012);
insert into car (make, model, price) values ('Lincoln', 'Town Car', 90339);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 84357);
insert into car (make, model, price) values ('Oldsmobile', '88', 39394);
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', 64521);
insert into car (make, model, price) values ('Audi', 'S8', 84326);
insert into car (make, model, price) values ('Jeep', 'Cherokee', 31396);
insert into car (make, model, price) values ('Scion', 'FR-S', 79649);
insert into car (make, model, price) values ('Chevrolet', 'Venture', 9342);
insert into car (make, model, price) values ('Buick', 'Somerset', 1145);
insert into car (make, model, price) values ('Mercedes-Benz', 'W201', 47125);
insert into car (make, model, price) values ('Chrysler', 'LHS', 52551);
insert into car (make, model, price) values ('Buick', 'Regal', 77362);
insert into car (make, model, price) values ('Cadillac', 'XLR-V', 50873);
insert into car (make, model, price) values ('Lotus', 'Elise', 72661);
insert into car (make, model, price) values ('Isuzu', 'Trooper', 91617);
insert into car (make, model, price) values ('Ford', 'Expedition', 84518);
insert into car (make, model, price) values ('Acura', 'CL', 95202);
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', 33178);
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', 48897);
insert into car (make, model, price) values ('GMC', 'Yukon', 6832);
insert into car (make, model, price) values ('Audi', 'A8', 56124);
insert into car (make, model, price) values ('Dodge', 'Ram 2500', 94652);
insert into car (make, model, price) values ('Mercedes-Benz', 'GLK-Class', 25478);
insert into car (make, model, price) values ('Volkswagen', 'GTI', 3973);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 38474);
insert into car (make, model, price) values ('Saab', '9-7X', 69007);
insert into car (make, model, price) values ('Ford', 'Mustang', 75908);
insert into car (make, model, price) values ('GMC', 'Vandura G2500', 57489);
insert into car (make, model, price) values ('Ford', 'E150', 27330);
insert into car (make, model, price) values ('Dodge', 'Ram Van 1500', 20169);
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', 91463);
insert into car (make, model, price) values ('Mercury', 'Cougar', 10523);
insert into car (make, model, price) values ('Ford', 'E250', 9751);
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', 40150);
insert into car (make, model, price) values ('BMW', 'M3', 16388);
insert into car (make, model, price) values ('Volvo', '850', 56677);
insert into car (make, model, price) values ('Cadillac', 'DeVille', 40442);
insert into car (make, model, price) values ('Ford', 'F250', 94948);
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', 33360);
insert into car (make, model, price) values ('Lexus', 'GS', 91187);
insert into car (make, model, price) values ('Mercedes-Benz', '300SE', 45972);
insert into car (make, model, price) values ('Toyota', 'Corolla', 42576);
insert into car (make, model, price) values ('Kia', 'Rio', 35432);
insert into car (make, model, price) values ('GMC', 'Sierra 3500', 83425);
insert into car (make, model, price) values ('Mazda', 'Protege', 70989);
insert into car (make, model, price) values ('Lexus', 'LX', 52379);
insert into car (make, model, price) values ('Porsche', '911', 15893);
insert into car (make, model, price) values ('Porsche', 'Panamera', 61079);
insert into car (make, model, price) values ('Mitsubishi', 'GTO', 19350);
insert into car (make, model, price) values ('Isuzu', 'i-280', 35318);
insert into car (make, model, price) values ('GMC', 'Yukon', 36157);
insert into car (make, model, price) values ('Subaru', 'Baja', 84735);
insert into car (make, model, price) values ('Ford', 'Explorer Sport Trac', 50041);
insert into car (make, model, price) values ('Ford', 'Explorer', 39946);
insert into car (make, model, price) values ('Honda', 'Accord', 22239);
insert into car (make, model, price) values ('Lexus', 'HS', 41393);
insert into car (make, model, price) values ('Volkswagen', 'Jetta III', 18421);
insert into car (make, model, price) values ('Ford', 'E350', 91174);
insert into car (make, model, price) values ('Ford', 'F250', 59369);
insert into car (make, model, price) values ('Honda', 'Civic', 11702);
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', 56123);
insert into car (make, model, price) values ('Lexus', 'LX', 91321);
insert into car (make, model, price) values ('Infiniti', 'QX', 78226);
insert into car (make, model, price) values ('Isuzu', 'Ascender', 22312);
insert into car (make, model, price) values ('Dodge', 'Caravan', 7826);
insert into car (make, model, price) values ('Ford', 'Taurus', 85526);
insert into car (make, model, price) values ('Pontiac', 'Chevette', 6980);
insert into car (make, model, price) values ('Subaru', 'BRZ', 25330);
insert into car (make, model, price) values ('Dodge', 'Stratus', 95396);
insert into car (make, model, price) values ('Mazda', 'B-Series', 27678);
insert into car (make, model, price) values ('Isuzu', 'Rodeo', 71966);
insert into car (make, model, price) values ('Toyota', 'Avalon', 25929);
insert into car (make, model, price) values ('Land Rover', 'Freelander', 3308);
insert into car (make, model, price) values ('Jeep', 'Wrangler', 69923);
insert into car (make, model, price) values ('Suzuki', 'Forenza', 47774);
insert into car (make, model, price) values ('Nissan', 'Pathfinder', 74818);
insert into car (make, model, price) values ('Pontiac', 'Vibe', 71548);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 46317);
insert into car (make, model, price) values ('Ram', '2500', 97900);
insert into car (make, model, price) values ('Dodge', 'Charger', 34817);
insert into car (make, model, price) values ('Mitsubishi', 'GTO', 30482);
insert into car (make, model, price) values ('Pontiac', 'Grand Am', 64086);
insert into car (make, model, price) values ('Honda', 'Insight', 91693);
insert into car (make, model, price) values ('Lotus', 'Esprit', 69554);
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', 88023);
insert into car (make, model, price) values ('BMW', '545', 10504);
insert into car (make, model, price) values ('Saturn', 'L-Series', 90008);
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', 30937);
insert into car (make, model, price) values ('Daewoo', 'Nubira', 25054);
insert into car (make, model, price) values ('Toyota', 'Tundra', 82866);
insert into car (make, model, price) values ('Mercedes-Benz', 'W201', 97744);
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', 81673);
insert into car (make, model, price) values ('Nissan', 'Sentra', 12206);
insert into car (make, model, price) values ('Mazda', '626', 26961);
insert into car (make, model, price) values ('Toyota', 'Tercel', 12066);
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', 65622);
insert into car (make, model, price) values ('Audi', '100', 89528);
insert into car (make, model, price) values ('Mazda', '626', 80220);
insert into car (make, model, price) values ('Ford', 'F-Series', 24368);
insert into car (make, model, price) values ('Lexus', 'ES', 72598);
insert into car (make, model, price) values ('Toyota', 'Tundra', 79730);
insert into car (make, model, price) values ('Aston Martin', 'V12 Vantage', 63843);
insert into car (make, model, price) values ('Hyundai', 'Scoupe', 26720);
insert into car (make, model, price) values ('BMW', '7 Series', 70375);
insert into car (make, model, price) values ('Honda', 'Pilot', 92141);
insert into car (make, model, price) values ('Volkswagen', 'GTI', 65852);
insert into car (make, model, price) values ('Volvo', 'C70', 26715);
insert into car (make, model, price) values ('BMW', 'X5', 90252);
insert into car (make, model, price) values ('Kia', 'Sephia', 86690);
insert into car (make, model, price) values ('Land Rover', 'LR2', 64544);
insert into car (make, model, price) values ('BMW', '760', 78092);
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', 51624);
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', 12347);
insert into car (make, model, price) values ('Lotus', 'Exige', 21562);
insert into car (make, model, price) values ('Audi', 'TT', 99264);
insert into car (make, model, price) values ('Infiniti', 'FX', 22174);
insert into car (make, model, price) values ('Mercury', 'Sable', 35105);
insert into car (make, model, price) values ('Cadillac', 'Escalade EXT', 17134);
insert into car (make, model, price) values ('Mitsubishi', 'Montero', 27679);
insert into car (make, model, price) values ('Porsche', '944', 9976);
insert into car (make, model, price) values ('BMW', '760', 12267);
insert into car (make, model, price) values ('Honda', 'Ridgeline', 19739);
insert into car (make, model, price) values ('Chrysler', 'Concorde', 23484);
insert into car (make, model, price) values ('Volvo', 'C70', 82938);
insert into car (make, model, price) values ('Volkswagen', 'R32', 88571);
insert into car (make, model, price) values ('Lincoln', 'MKZ', 82528);
insert into car (make, model, price) values ('Nissan', 'Armada', 19293);
insert into car (make, model, price) values ('Saab', '9-4X', 53508);
insert into car (make, model, price) values ('GMC', 'Safari', 16119);
insert into car (make, model, price) values ('Mercury', 'Mountaineer', 11921);
insert into car (make, model, price) values ('Mitsubishi', 'GTO', 2549);
insert into car (make, model, price) values ('Ford', 'Club Wagon', 6774);
insert into car (make, model, price) values ('Nissan', 'Quest', 54184);
insert into car (make, model, price) values ('Pontiac', 'LeMans', 61778);
insert into car (make, model, price) values ('Chevrolet', 'Colorado', 78298);
insert into car (make, model, price) values ('Buick', 'Riviera', 78200);
insert into car (make, model, price) values ('Honda', 'Civic Si', 33430);
insert into car (make, model, price) values ('Chrysler', 'Concorde', 59239);
insert into car (make, model, price) values ('Ford', 'Contour', 82516);
insert into car (make, model, price) values ('Volvo', 'XC60', 44350);
insert into car (make, model, price) values ('Dodge', 'Ram 3500', 1303);
insert into car (make, model, price) values ('Land Rover', 'LR3', 84654);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 73406);
insert into car (make, model, price) values ('Porsche', '911', 79499);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 66781);
insert into car (make, model, price) values ('Nissan', 'Frontier', 33795);
insert into car (make, model, price) values ('Isuzu', 'Hombre', 57184);
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', 70167);
insert into car (make, model, price) values ('Lotus', 'Elan', 88699);
insert into car (make, model, price) values ('Ford', 'F350', 79255);
insert into car (make, model, price) values ('BMW', '6 Series', 33879);
insert into car (make, model, price) values ('Mitsubishi', 'GTO', 71563);
insert into car (make, model, price) values ('Nissan', 'Frontier', 99146);
insert into car (make, model, price) values ('Dodge', 'Challenger', 27493);
insert into car (make, model, price) values ('Lotus', 'Esprit', 67628);
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', 82679);
insert into car (make, model, price) values ('Plymouth', 'Horizon', 10805);
insert into car (make, model, price) values ('Volvo', 'C70', 61645);
insert into car (make, model, price) values ('Dodge', 'Viper', 40004);
insert into car (make, model, price) values ('Nissan', 'Murano', 77971);
insert into car (make, model, price) values ('Volvo', 'S70', 31090);
insert into car (make, model, price) values ('Ford', 'E250', 25190);
insert into car (make, model, price) values ('Lincoln', 'MKX', 95673);
insert into car (make, model, price) values ('Acura', 'TL', 46597);
insert into car (make, model, price) values ('Audi', 'A6', 22816);
insert into car (make, model, price) values ('Jeep', 'Wrangler', 70952);
insert into car (make, model, price) values ('Subaru', 'Impreza', 98083);
insert into car (make, model, price) values ('Subaru', 'Loyale', 40459);
insert into car (make, model, price) values ('Nissan', 'Rogue', 76955);
insert into car (make, model, price) values ('Buick', 'Coachbuilder', 12703);
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 1500', 6099);
insert into car (make, model, price) values ('Chevrolet', 'Camaro', 12854);
insert into car (make, model, price) values ('Ferrari', '612 Scaglietti', 86375);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', 33638);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 17407);
insert into car (make, model, price) values ('Ford', 'F-Series', 90367);
insert into car (make, model, price) values ('Mitsubishi', 'Galant', 52012);
insert into car (make, model, price) values ('Toyota', 'Sequoia', 48977);
insert into car (make, model, price) values ('Audi', 'S6', 48918);
insert into car (make, model, price) values ('Buick', 'Century', 45407);
insert into car (make, model, price) values ('Lamborghini', 'Murciélago', 85212);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLS AMG', 17138);
insert into car (make, model, price) values ('Nissan', 'Altima', 7485);
insert into car (make, model, price) values ('Chevrolet', 'Suburban', 76210);
insert into car (make, model, price) values ('Honda', 'Civic', 82753);
insert into car (make, model, price) values ('Honda', 'Accord', 9548);
insert into car (make, model, price) values ('Land Rover', 'Freelander', 56703);
insert into car (make, model, price) values ('Audi', 'S5', 24595);
insert into car (make, model, price) values ('Toyota', 'Celica', 47327);
insert into car (make, model, price) values ('Hyundai', 'HED-5', 36538);
insert into car (make, model, price) values ('Mitsubishi', 'Montero', 48288);
insert into car (make, model, price) values ('Mercedes-Benz', 'GLK-Class', 92806);
insert into car (make, model, price) values ('Jaguar', 'X-Type', 81951);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', 81532);
insert into car (make, model, price) values ('Pontiac', 'Bonneville', 51295);
insert into car (make, model, price) values ('Mitsubishi', 'Endeavor', 1749);
insert into car (make, model, price) values ('BMW', '745', 36726);
insert into car (make, model, price) values ('Hyundai', 'Accent', 84512);
insert into car (make, model, price) values ('Toyota', 'Supra', 26640);
insert into car (make, model, price) values ('Ford', 'GT', 18934);
insert into car (make, model, price) values ('Ford', 'F350', 96920);
insert into car (make, model, price) values ('Lotus', 'Elise', 82752);
insert into car (make, model, price) values ('Acura', 'CL', 36171);
insert into car (make, model, price) values ('GMC', 'Savana 3500', 31867);
insert into car (make, model, price) values ('GMC', 'Savana 2500', 23719);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLS AMG', 98051);
insert into car (make, model, price) values ('Toyota', 'Corolla', 4764);
insert into car (make, model, price) values ('Buick', 'Riviera', 10526);
insert into car (make, model, price) values ('Mercedes-Benz', 'W201', 94989);
insert into car (make, model, price) values ('GMC', 'Envoy', 12710);
insert into car (make, model, price) values ('Subaru', 'XT', 27563);
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', 76996);
insert into car (make, model, price) values ('GMC', 'Yukon', 58444);
insert into car (make, model, price) values ('Toyota', 'Echo', 61425);
insert into car (make, model, price) values ('Audi', 'riolet', 32480);
insert into car (make, model, price) values ('Audi', 'Coupe GT', 77855);
insert into car (make, model, price) values ('Plymouth', 'Grand Voyager', 83759);
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', 79654);
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', 80463);
insert into car (make, model, price) values ('Subaru', 'Outback', 59324);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLR McLaren', 9222);
insert into car (make, model, price) values ('Volvo', 'XC70', 14670);
insert into car (make, model, price) values ('Mitsubishi', 'Chariot', 61745);
insert into car (make, model, price) values ('Volkswagen', 'Corrado', 62582);
insert into car (make, model, price) values ('Dodge', 'Stealth', 2000);
insert into car (make, model, price) values ('Maserati', 'Coupe', 83600);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK55 AMG', 35378);
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', 91823);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 3500', 58945);
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', 51990);
insert into car (make, model, price) values ('Volkswagen', 'Scirocco', 7076);
insert into car (make, model, price) values ('Chrysler', 'Imperial', 35457);
insert into car (make, model, price) values ('Suzuki', 'SJ', 23784);
insert into car (make, model, price) values ('Nissan', 'Altima', 49353);
insert into car (make, model, price) values ('Audi', 'Cabriolet', 52995);
insert into car (make, model, price) values ('Toyota', 'Camry Hybrid', 62994);
insert into car (make, model, price) values ('Kia', 'Optima', 52890);
insert into car (make, model, price) values ('BMW', 'Z4 M', 90192);
insert into car (make, model, price) values ('Ford', 'F-Series', 67275);
insert into car (make, model, price) values ('Scion', 'xB', 39462);
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', 94849);
insert into car (make, model, price) values ('Subaru', 'Justy', 27700);
insert into car (make, model, price) values ('Ford', 'Bronco II', 41240);
insert into car (make, model, price) values ('Mazda', 'MPV', 41080);
insert into car (make, model, price) values ('GMC', 'Savana 2500', 50807);
insert into car (make, model, price) values ('Plymouth', 'Neon', 12162);
insert into car (make, model, price) values ('Infiniti', 'EX', 62975);
insert into car (make, model, price) values ('Volvo', 'V70', 17195);
insert into car (make, model, price) values ('Chevrolet', 'Astro', 43122);
insert into car (make, model, price) values ('Toyota', 'Tacoma', 91247);
insert into car (make, model, price) values ('Isuzu', 'Amigo', 7977);
insert into car (make, model, price) values ('Mazda', 'B-Series', 97878);
insert into car (make, model, price) values ('GMC', 'Envoy XL', 24577);
insert into car (make, model, price) values ('Chevrolet', 'Tracker', 64186);
insert into car (make, model, price) values ('Fairthorpe', 'Rockette', 75301);
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', 10058);
insert into car (make, model, price) values ('Toyota', 'RAV4', 94610);
insert into car (make, model, price) values ('Pontiac', 'Grand Am', 39717);
insert into car (make, model, price) values ('Ford', 'Fairlane', 90510);
insert into car (make, model, price) values ('Pontiac', 'LeMans', 96914);
insert into car (make, model, price) values ('Toyota', 'Prius Plug-in Hybrid', 82781);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', 85023);
insert into car (make, model, price) values ('GMC', 'Savana 2500', 13484);
insert into car (make, model, price) values ('Dodge', 'Dakota Club', 58352);
insert into car (make, model, price) values ('Chevrolet', 'Astro', 97127);
insert into car (make, model, price) values ('Nissan', 'Frontier', 69561);
insert into car (make, model, price) values ('Kia', 'Sorento', 89631);
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', 74493);
insert into car (make, model, price) values ('Toyota', 'RAV4', 94151);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', 67704);
insert into car (make, model, price) values ('Ford', 'F150', 94008);
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', 10400);
insert into car (make, model, price) values ('Toyota', 'Corolla', 39872);
insert into car (make, model, price) values ('Volvo', '850', 46549);
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', 87086);
insert into car (make, model, price) values ('Maserati', 'GranSport', 69921);
insert into car (make, model, price) values ('Audi', 'A4', 18389);
insert into car (make, model, price) values ('Cadillac', 'DTS', 3268);
insert into car (make, model, price) values ('Ford', 'Ranger', 83173);
insert into car (make, model, price) values ('Pontiac', 'Vibe', 15186);
insert into car (make, model, price) values ('Eagle', 'Vision', 78067);
insert into car (make, model, price) values ('Land Rover', 'Range Rover Sport', 16618);
insert into car (make, model, price) values ('GMC', 'Yukon', 41425);
insert into car (make, model, price) values ('Acura', 'MDX', 9697);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 54997);
insert into car (make, model, price) values ('Eagle', 'Premier', 17520);
insert into car (make, model, price) values ('Mercedes-Benz', '500E', 84715);
insert into car (make, model, price) values ('Nissan', 'Quest', 41824);
insert into car (make, model, price) values ('Subaru', 'Legacy', 6864);
insert into car (make, model, price) values ('Volvo', '960', 34012);
insert into car (make, model, price) values ('GMC', 'Safari', 16453);
insert into car (make, model, price) values ('Jaguar', 'S-Type', 60699);
insert into car (make, model, price) values ('BMW', '5 Series', 36383);
insert into car (make, model, price) values ('Lamborghini', 'Diablo', 2276);
insert into car (make, model, price) values ('Chevrolet', 'Malibu', 77557);
insert into car (make, model, price) values ('Chevrolet', 'S10', 59302);
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', 3321);
insert into car (make, model, price) values ('Mazda', 'Millenia', 56590);
insert into car (make, model, price) values ('Ford', 'Focus', 35986);
insert into car (make, model, price) values ('Mazda', '929', 16659);
insert into car (make, model, price) values ('Aston Martin', 'V8 Vantage', 89021);
insert into car (make, model, price) values ('Mercedes-Benz', '300TE', 10665);
insert into car (make, model, price) values ('Chrysler', 'Grand Voyager', 16096);
insert into car (make, model, price) values ('Cadillac', 'Escalade EXT', 31388);
insert into car (make, model, price) values ('Infiniti', 'QX', 44177);
insert into car (make, model, price) values ('Suzuki', 'Esteem', 21605);
insert into car (make, model, price) values ('BMW', '7 Series', 22132);
insert into car (make, model, price) values ('Ford', 'Crown Victoria', 1297);
insert into car (make, model, price) values ('Pontiac', 'G3', 42286);
insert into car (make, model, price) values ('Audi', 'S4', 58720);
insert into car (make, model, price) values ('Lincoln', 'MKT', 30927);
insert into car (make, model, price) values ('Maserati', 'Gran Sport', 58340);
insert into car (make, model, price) values ('Nissan', 'Frontier', 43054);
insert into car (make, model, price) values ('Cadillac', 'Seville', 47841);
insert into car (make, model, price) values ('Oldsmobile', '98', 41328);
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', 50721);
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', 26542);
insert into car (make, model, price) values ('Ford', 'E350', 84754);
insert into car (make, model, price) values ('Infiniti', 'FX', 6758);
insert into car (make, model, price) values ('Ford', 'Econoline E350', 75992);
insert into car (make, model, price) values ('Audi', 'A3', 65479);
insert into car (make, model, price) values ('Kia', 'Sportage', 77010);
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', 89943);
insert into car (make, model, price) values ('Ford', 'Aerostar', 76057);
insert into car (make, model, price) values ('Dodge', 'Neon', 44132);
insert into car (make, model, price) values ('Toyota', 'FJ Cruiser', 64128);
insert into car (make, model, price) values ('Ford', 'EXP', 25697);
insert into car (make, model, price) values ('Honda', 'Odyssey', 66252);
insert into car (make, model, price) values ('Infiniti', 'QX', 7229);
insert into car (make, model, price) values ('Ford', 'F150', 54062);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', 61066);
insert into car (make, model, price) values ('Suzuki', 'XL-7', 6194);
insert into car (make, model, price) values ('Toyota', 'Sequoia', 49029);
insert into car (make, model, price) values ('Jaguar', 'S-Type', 3264);
insert into car (make, model, price) values ('Lotus', 'Esprit', 26761);
insert into car (make, model, price) values ('Lexus', 'IS', 35200);
insert into car (make, model, price) values ('GMC', 'Rally Wagon 3500', 46552);
insert into car (make, model, price) values ('Chevrolet', 'K5 Blazer', 91983);
insert into car (make, model, price) values ('Toyota', 'Prius', 31731);
insert into car (make, model, price) values ('Ford', 'Econoline E350', 42744);
insert into car (make, model, price) values ('Acura', 'Integra', 74621);
insert into car (make, model, price) values ('Dodge', 'Ram', 42938);
insert into car (make, model, price) values ('Aston Martin', 'Rapide', 97685);
insert into car (make, model, price) values ('Mitsubishi', 'Galant', 41191);
insert into car (make, model, price) values ('Mitsubishi', 'Outlander', 54150);
insert into car (make, model, price) values ('Mazda', 'Tribute', 45080);
insert into car (make, model, price) values ('Cadillac', 'Escalade ESV', 36702);
insert into car (make, model, price) values ('Oldsmobile', 'Aurora', 50090);
insert into car (make, model, price) values ('Volvo', '960', 20776);
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', 97975);
insert into car (make, model, price) values ('Lexus', 'GS', 61573);
insert into car (make, model, price) values ('Scion', 'xB', 69513);
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', 30968);
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', 33440);
insert into car (make, model, price) values ('Porsche', '911', 68837);
insert into car (make, model, price) values ('BMW', '7 Series', 9408);
insert into car (make, model, price) values ('BMW', 'M3', 47670);
insert into car (make, model, price) values ('Buick', 'Regal', 80472);
insert into car (make, model, price) values ('Bentley', 'Continental GT', 86567);
insert into car (make, model, price) values ('Mercedes-Benz', 'GL-Class', 50479);
insert into car (make, model, price) values ('Lexus', 'RX', 17770);
insert into car (make, model, price) values ('BMW', 'Z3', 22097);
insert into car (make, model, price) values ('Buick', 'Skylark', 62524);
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', 58848);
insert into car (make, model, price) values ('Nissan', 'Maxima', 21597);
insert into car (make, model, price) values ('Hyundai', 'Tucson', 66547);
insert into car (make, model, price) values ('Volvo', '850', 89528);
insert into car (make, model, price) values ('Volkswagen', 'Fox', 75081);
insert into car (make, model, price) values ('Daewoo', 'Lanos', 56251);
insert into car (make, model, price) values ('Aston Martin', 'Vantage', 27053);
insert into car (make, model, price) values ('Saab', '900', 86946);
insert into car (make, model, price) values ('Pontiac', '6000', 79349);
insert into car (make, model, price) values ('Lotus', 'Esprit', 96894);
insert into car (make, model, price) values ('Toyota', 'Sequoia', 31742);
insert into car (make, model, price) values ('Acura', 'TL', 97463);
insert into car (make, model, price) values ('Volkswagen', 'Rabbit', 21572);
insert into car (make, model, price) values ('Lincoln', 'Continental', 39109);
insert into car (make, model, price) values ('Honda', 'Odyssey', 44842);
insert into car (make, model, price) values ('Audi', 'riolet', 53367);
insert into car (make, model, price) values ('Ford', 'Aspire', 95558);
insert into car (make, model, price) values ('Buick', 'Electra', 10839);
insert into car (make, model, price) values ('Ford', 'F-Series', 52726);
insert into car (make, model, price) values ('Ford', 'F250', 38943);
insert into car (make, model, price) values ('Nissan', 'GT-R', 25566);
insert into car (make, model, price) values ('Maserati', 'Quattroporte', 89217);
insert into car (make, model, price) values ('Mazda', 'B2500', 80597);
insert into car (make, model, price) values ('Audi', 'A4', 57308);
insert into car (make, model, price) values ('Mercury', 'Mountaineer', 42535);
insert into car (make, model, price) values ('Pontiac', 'GTO', 96613);
insert into car (make, model, price) values ('Dodge', 'Neon', 39029);
insert into car (make, model, price) values ('Acura', 'NSX', 44568);
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', 44136);
insert into car (make, model, price) values ('Nissan', 'Altima', 78312);
insert into car (make, model, price) values ('Ford', 'Taurus', 94093);
insert into car (make, model, price) values ('Saab', '900', 96641);
insert into car (make, model, price) values ('Nissan', 'Armada', 76215);
insert into car (make, model, price) values ('BMW', 'M', 67058);
insert into car (make, model, price) values ('Ford', 'F350', 82420);
insert into car (make, model, price) values ('Scion', 'tC', 31325);
insert into car (make, model, price) values ('Nissan', 'Rogue', 15995);
insert into car (make, model, price) values ('BMW', '600', 59115);
insert into car (make, model, price) values ('Porsche', '928', 84080);
insert into car (make, model, price) values ('GMC', '2500', 55242);
insert into car (make, model, price) values ('Infiniti', 'G', 69039);
insert into car (make, model, price) values ('Dodge', 'Ram Van B150', 7985);
insert into car (make, model, price) values ('Honda', 'S2000', 43485);
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', 77244);
insert into car (make, model, price) values ('Cadillac', 'DeVille', 19957);
insert into car (make, model, price) values ('Nissan', 'Sentra', 9240);
insert into car (make, model, price) values ('Mitsubishi', 'Outlander', 52949);
insert into car (make, model, price) values ('Kia', 'Rio', 39438);
insert into car (make, model, price) values ('Acura', 'TSX', 80487);
insert into car (make, model, price) values ('Pontiac', 'Montana', 67275);
insert into car (make, model, price) values ('Scion', 'tC', 10751);
insert into car (make, model, price) values ('Volvo', 'C70', 34224);
insert into car (make, model, price) values ('Isuzu', 'Hombre', 7714);
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', 53505);
insert into car (make, model, price) values ('Dodge', 'Ram 3500', 63115);
insert into car (make, model, price) values ('Ford', 'Explorer', 2685);
insert into car (make, model, price) values ('Mitsubishi', 'Truck', 42641);
insert into car (make, model, price) values ('Porsche', '911', 89627);
insert into car (make, model, price) values ('BMW', 'Z8', 91782);
insert into car (make, model, price) values ('Toyota', 'Tacoma', 75804);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 20112);
insert into car (make, model, price) values ('Chevrolet', 'Express', 18638);
insert into car (make, model, price) values ('GMC', 'Sonoma Club Coupe', 18184);
insert into car (make, model, price) values ('Porsche', 'Boxster', 37999);
insert into car (make, model, price) values ('Chrysler', 'PT Cruiser', 75621);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 3500HD', 47661);
insert into car (make, model, price) values ('Porsche', 'Cayenne', 28972);
insert into car (make, model, price) values ('Bentley', 'Continental GT', 95034);
insert into car (make, model, price) values ('Chrysler', 'Concorde', 30608);
insert into car (make, model, price) values ('Chevrolet', '2500', 3313);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', 84443);
insert into car (make, model, price) values ('MINI', 'Cooper', 70864);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', 30497);
insert into car (make, model, price) values ('Land Rover', 'Discovery', 90446);
insert into car (make, model, price) values ('Nissan', 'Xterra', 73301);
insert into car (make, model, price) values ('Oldsmobile', 'Aurora', 39937);
insert into car (make, model, price) values ('Ford', 'E250', 16875);
insert into car (make, model, price) values ('Mercedes-Benz', '300SE', 16964);
insert into car (make, model, price) values ('Kia', 'Spectra', 99070);
insert into car (make, model, price) values ('Mercury', 'Topaz', 50389);
insert into car (make, model, price) values ('Mitsubishi', 'Lancer Evolution', 90036);
insert into car (make, model, price) values ('Mitsubishi', 'Galant', 51081);
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', 76383);
insert into car (make, model, price) values ('Aptera', 'Typ-1', 7808);
insert into car (make, model, price) values ('Audi', 'R8', 26915);
insert into car (make, model, price) values ('Volkswagen', 'Golf', 96394);
insert into car (make, model, price) values ('Cadillac', 'STS', 68259);
insert into car (make, model, price) values ('Toyota', 'Solara', 16072);
insert into car (make, model, price) values ('Oldsmobile', 'Ciera', 65504);
insert into car (make, model, price) values ('Isuzu', 'VehiCROSS', 5065);
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', 22175);
insert into car (make, model, price) values ('Mercury', 'Cougar', 59318);
insert into car (make, model, price) values ('Toyota', 'Tacoma', 37967);
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', 37673);
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', 63880);
insert into car (make, model, price) values ('Buick', 'Park Avenue', 22971);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', 91093);
insert into car (make, model, price) values ('Ferrari', '612 Scaglietti', 81383);
insert into car (make, model, price) values ('Buick', 'LeSabre', 83555);
insert into car (make, model, price) values ('Mazda', 'MX-5', 30673);
insert into car (make, model, price) values ('Ford', 'Escort', 79315);
insert into car (make, model, price) values ('Ford', 'E-Series', 48737);
insert into car (make, model, price) values ('Infiniti', 'G25', 37562);
insert into car (make, model, price) values ('Infiniti', 'QX', 22940);
insert into car (make, model, price) values ('Ford', 'Fairlane', 74069);
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', 11798);
insert into car (make, model, price) values ('Saab', '900', 100000);
insert into car (make, model, price) values ('Ferrari', '599 GTB Fiorano', 52726);
insert into car (make, model, price) values ('GMC', 'Sierra 3500', 13560);
insert into car (make, model, price) values ('Mitsubishi', 'Endeavor', 63914);
insert into car (make, model, price) values ('Oldsmobile', 'LSS', 97293);
insert into car (make, model, price) values ('Suzuki', 'Sidekick', 87351);
insert into car (make, model, price) values ('Ford', 'Bronco II', 65292);
insert into car (make, model, price) values ('Subaru', 'Legacy', 17817);
insert into car (make, model, price) values ('Chevrolet', 'S10', 20425);
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', 82100);
insert into car (make, model, price) values ('Mitsubishi', 'Galant', 53195);
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', 51332);
insert into car (make, model, price) values ('GMC', 'Suburban 2500', 55486);
insert into car (make, model, price) values ('GMC', 'Yukon', 29812);
insert into car (make, model, price) values ('Chevrolet', 'G-Series G20', 77201);
insert into car (make, model, price) values ('Nissan', 'Quest', 62245);
insert into car (make, model, price) values ('Toyota', 'TundraMax', 42257);
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', 65446);
insert into car (make, model, price) values ('Mazda', 'B-Series', 94234);
insert into car (make, model, price) values ('Ford', 'Escort', 67330);
insert into car (make, model, price) values ('Honda', 'del Sol', 11156);
insert into car (make, model, price) values ('Cadillac', 'CTS', 14524);
insert into car (make, model, price) values ('Dodge', 'Dakota', 30378);
insert into car (make, model, price) values ('Toyota', 'Highlander', 85335);
insert into car (make, model, price) values ('Lexus', 'ES', 31836);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', 82424);
insert into car (make, model, price) values ('Lotus', 'Esprit', 62468);
insert into car (make, model, price) values ('Ford', 'F250', 38977);
insert into car (make, model, price) values ('GMC', 'Yukon', 7075);
insert into car (make, model, price) values ('Maserati', 'Quattroporte', 39089);
insert into car (make, model, price) values ('Bentley', 'Azure', 17563);
insert into car (make, model, price) values ('Dodge', 'Sprinter', 44052);
insert into car (make, model, price) values ('Ford', 'F150', 78163);
insert into car (make, model, price) values ('GMC', 'Savana 3500', 42585);
insert into car (make, model, price) values ('Chevrolet', 'HHR', 94833);
insert into car (make, model, price) values ('BMW', 'Z4', 34210);
insert into car (make, model, price) values ('Chrysler', 'Cirrus', 35155);
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', 56290);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 2814);
insert into car (make, model, price) values ('Nissan', 'Altima', 45559);
insert into car (make, model, price) values ('Pontiac', 'Bonneville', 70600);
insert into car (make, model, price) values ('Chrysler', 'Voyager', 6066);
insert into car (make, model, price) values ('Honda', 'del Sol', 62310);
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', 14426);
insert into car (make, model, price) values ('Toyota', 'RAV4', 32369);
insert into car (make, model, price) values ('Hyundai', 'Azera', 11840);
insert into car (make, model, price) values ('GMC', 'Savana 3500', 49143);
insert into car (make, model, price) values ('Chrysler', 'LeBaron', 34061);
insert into car (make, model, price) values ('Bentley', 'Continental Flying Spur', 32805);
insert into car (make, model, price) values ('Lexus', 'GX', 29996);
insert into car (make, model, price) values ('BMW', 'M5', 20077);
insert into car (make, model, price) values ('Mazda', 'Mazda6', 76458);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', 38577);
insert into car (make, model, price) values ('Chrysler', 'Cirrus', 91206);
insert into car (make, model, price) values ('Subaru', 'XT', 75516);
insert into car (make, model, price) values ('Ford', 'Econoline E250', 77071);
insert into car (make, model, price) values ('GMC', 'Canyon', 89853);
insert into car (make, model, price) values ('Saab', '9000', 49916);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 54126);
insert into car (make, model, price) values ('Buick', 'Coachbuilder', 23639);
insert into car (make, model, price) values ('Mitsubishi', 'Cordia', 17755);
insert into car (make, model, price) values ('Ford', 'Explorer', 67900);
insert into car (make, model, price) values ('Land Rover', 'Sterling', 91823);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 27911);
insert into car (make, model, price) values ('Porsche', 'Boxster', 49857);
insert into car (make, model, price) values ('Mitsubishi', 'Outlander', 73401);
insert into car (make, model, price) values ('Acura', 'Integra', 29028);
insert into car (make, model, price) values ('Bentley', 'Azure', 58202);
insert into car (make, model, price) values ('Ford', 'Thunderbird', 99059);
insert into car (make, model, price) values ('Dodge', 'Challenger', 32606);
insert into car (make, model, price) values ('Saturn', 'S-Series', 49893);
insert into car (make, model, price) values ('Ford', 'GT', 66834);
insert into car (make, model, price) values ('Mercury', 'Mountaineer', 76024);
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', 43674);
insert into car (make, model, price) values ('Chevrolet', 'Malibu', 28230);
insert into car (make, model, price) values ('Hyundai', 'Veracruz', 44418);
insert into car (make, model, price) values ('Dodge', 'Ram 3500 Club', 51056);
insert into car (make, model, price) values ('Subaru', 'Leone', 20473);
insert into car (make, model, price) values ('Ford', 'Falcon', 8602);
insert into car (make, model, price) values ('Subaru', 'Legacy', 90540);
insert into car (make, model, price) values ('Jeep', 'Wrangler', 83104);
insert into car (make, model, price) values ('Land Rover', 'Discovery Series II', 12175);
insert into car (make, model, price) values ('Nissan', 'Altima', 93050);
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', 58090);
insert into car (make, model, price) values ('GMC', 'Yukon', 59944);
insert into car (make, model, price) values ('GMC', '2500 Club Coupe', 76192);
insert into car (make, model, price) values ('Cadillac', 'Seville', 38276);
insert into car (make, model, price) values ('Chrysler', 'Sebring', 77433);
insert into car (make, model, price) values ('Daewoo', 'Lanos', 12797);
insert into car (make, model, price) values ('Hyundai', 'Entourage', 18220);
insert into car (make, model, price) values ('Nissan', 'Sentra', 4564);
insert into car (make, model, price) values ('Suzuki', 'X-90', 49007);
insert into car (make, model, price) values ('Dodge', 'Ram 1500', 63540);
insert into car (make, model, price) values ('Hyundai', 'Tiburon', 43904);
insert into car (make, model, price) values ('Jaguar', 'XJ Series', 49611);
insert into car (make, model, price) values ('Mercury', 'Milan', 67324);
insert into car (make, model, price) values ('Audi', 'Q7', 99875);
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', 9520);
insert into car (make, model, price) values ('Nissan', 'Xterra', 26054);
insert into car (make, model, price) values ('Dodge', 'Caliber', 98763);
insert into car (make, model, price) values ('Volkswagen', 'Jetta', 27088);
insert into car (make, model, price) values ('Audi', 'S5', 55520);
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', 65256);
insert into car (make, model, price) values ('Honda', 'Accord', 75686);
insert into car (make, model, price) values ('Chevrolet', 'Equinox', 84248);
insert into car (make, model, price) values ('Mercury', 'Cougar', 19440);
insert into car (make, model, price) values ('BMW', '525', 93718);
insert into car (make, model, price) values ('Mercury', 'Cougar', 29612);
insert into car (make, model, price) values ('BMW', 'X5', 81273);
insert into car (make, model, price) values ('Saturn', 'S-Series', 89809);
insert into car (make, model, price) values ('Ford', 'E250', 14249);
insert into car (make, model, price) values ('Cadillac', 'XLR', 26984);
insert into car (make, model, price) values ('Audi', 'A4', 9575);
insert into car (make, model, price) values ('GMC', 'Safari', 16047);
insert into car (make, model, price) values ('Aston Martin', 'Vantage', 68949);
insert into car (make, model, price) values ('Rolls-Royce', 'Phantom', 79809);
insert into car (make, model, price) values ('Subaru', 'Tribeca', 73046);
insert into car (make, model, price) values ('Hyundai', 'Tiburon', 83657);
insert into car (make, model, price) values ('Aston Martin', 'Vantage', 75330);
insert into car (make, model, price) values ('Audi', 'R8', 61526);
insert into car (make, model, price) values ('Isuzu', 'Trooper', 51260);
insert into car (make, model, price) values ('Hummer', 'H3', 84230);
insert into car (make, model, price) values ('Pontiac', '6000', 3900);
insert into car (make, model, price) values ('Mitsubishi', 'Cordia', 79792);
insert into car (make, model, price) values ('Dodge', 'Ram Van 3500', 93711);
insert into car (make, model, price) values ('Chevrolet', 'Metro', 71163);
insert into car (make, model, price) values ('Volkswagen', 'Corrado', 77403);
insert into car (make, model, price) values ('Chevrolet', 'Avalanche', 34357);
insert into car (make, model, price) values ('Cadillac', 'Catera', 97572);
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', 35740);
insert into car (make, model, price) values ('Porsche', '911', 96696);
insert into car (make, model, price) values ('Mitsubishi', 'Galant', 28780);
insert into car (make, model, price) values ('Saab', '9000', 99055);
insert into car (make, model, price) values ('Lexus', 'SC', 96766);
insert into car (make, model, price) values ('Volkswagen', 'Touareg 2', 80554);
insert into car (make, model, price) values ('Hyundai', 'Tucson', 10198);
insert into car (make, model, price) values ('Chevrolet', 'Equinox', 32164);
insert into car (make, model, price) values ('Ford', 'Expedition', 80635);
insert into car (make, model, price) values ('Isuzu', 'Oasis', 99436);
insert into car (make, model, price) values ('Mazda', 'Mazdaspeed 3', 19930);
insert into car (make, model, price) values ('Ferrari', '599 GTB Fiorano', 83542);
insert into car (make, model, price) values ('Volkswagen', 'Type 2', 51373);
